# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Control all joints
arm_controller:
  type: arm_control/ArmController

# Position Controllers
#toe_foot_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: toe_foot_joint
#  pid: {p: 50.0, i: 0.0, d: 7.5}
#foot_leg_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: foot_leg_joint
#  pid: {p: 500.0, i: 0.0, d: 10.0}
#leg_arm_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: leg_arm_joint
#  pid: {p: 500.0, i: 0.0, d: 10.0}
#arm_hand_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: arm_hand_joint
#  pid: {p: 10.0, i: 0.0, d: 1.0}
#hand_finger_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: hand_finger_joint
#  pid: {p: 10.0, i: 0.0, d: 1.0}